import React from "react";
import { Layout } from "../components/layout";

export default function About(){
  return(
    <Layout>
      <div>
        about<br/>
        about<br/>
        about<br/>
        about<br/>
        about<br/>
        about<br/>
        about<br/>
        about<br/>
        about<br/>
        about<br/>
        about<br/>
        about<br/>
        about<br/>
        about<br/>
        about<br/>
        about<br/>
        about<br/>
        about<br/>
        about<br/>
        about<br/>
        about<br/>
        about<br/>
        about<br/>
        about<br/>
        about<br/>
        about<br/>
        about<br/>
        about<br/>
        about<br/>
        about<br/>
        about<br/>
        about<br/>
        about<br/>
        about<br/>
        about<br/>
        about<br/>
        about<br/>
        about<br/>
        about<br/>
        about<br/>
        about<br/>
        about<br/>
        about<br/>
        about<br/>
      </div>
    </Layout>
  )
}